### ISSUE TITLE
access to dropbox?

### ISSUE THREAD

**Issue by fkloosterman** [intake/filesystem_spec#200]
I was wondering if there is already a filesystem implementation that provides access to dropbox (I suppose using the dropbox API)? If not, what alternatives for dropbox access with fsspec exist?

**Comment by martindurant** [comment]
There is no such implementation.
However, the implementations in this repo, as well as the new https://github.com/intake/gdrivefs (in development) should show that they are not hard to make, so long as the remote API is reasonably flexible. The [python library](https://dropbox-sdk-python.readthedocs.io/en/stable/) does look OK at a glance.

**Comment by MarineChap** [comment]
Dear, 
I am working with @fkloosterman. We developed our (partial) implementation for dropbox. For the moment, I cloned the filesystem_spec and manually add in the "registry.py" my own implementation. It is working well but there is another way to add an implementation ? I would rather prefer to use your package instead of a local modified package. 
(I would also be happy to share with you the implementation if you are interested but it is really a partial implementation. We only want to use it for upload file in dropbox).
Thanks

**Comment by martindurant** [comment]
Please post a PR to here, with a change to fsspec.registry.known_implementations specifying the import/class of the implementation, a protocol (I suggest "dropbox") and a meaningful message upon import failure, telling people how to install your package.
Happy to see it included!

**Comment by martindurant** [comment]
ref #206

**Comment by MarineChap** [comment]
Hello! Nice, my first open-source PR!! ;) Forgive me I am a newbie in open-source. As it is a short implementation, I was not thinking to create my own package for this. It is not possible to add it in the PR to be part of the available fsspec implementation ? Like this, eventually someone can add the missing part later, no?

**Comment by martindurant** [comment]
Sorry, I had assumed that you already had a package.
In this case, you would need to not only do what I suggested above for the registry, but include your implementation in the PR too, in the directory fsspec/implementations/ . Obviously, if the implementation is incomplete, you should explicitly document how. Also, you should document how to install necessary dependencies (an abbreviated version would go in the error message in the registry too).
The best thing would be to get started, so comments can go alongside the code.

**Comment by MarineChap** [comment]
#226
