### ISSUE TITLE
Feature request: Share point

### ISSUE THREAD

**Issue by raybellwaves** [intake/filesystem_spec#280]
I believe there is a package for getting data in/out of share point https://github.com/ox-it/python-sharepoint could create a fsspec version of it

**Comment by martindurant** [comment]
Are you offering to try to implement this? I don't know the first thing about sharepoint, but could be a nice addition indeed.

**Comment by martindurant** [comment]
There is also shareplum, but both it and python-sharepoint are rather old and incomplete ; but it seems like direct REST interaction might be the easiest thing to implement, https://stackoverflow.com/a/21505184/3821154

**Comment by martindurant** [comment]
@raybellwaves , are you still thinking about this?

**Comment by raybellwaves** [comment]
I'm not sadly

**Comment by martindurant** [comment]
Feel free to reopen if you even are planning to

**Comment by HaddocktheHorrible** [comment]
Hello, there's a number of us using [DVC ](https://github.com/iterative/dvc) that are eager for sharepoint support in fsspec. Any suggestions for how we might get be able to get traction on this issue?

**Comment by efiop** [comment]
@HaddocktheHorrible Someone needs to dedicate their time to implementing and maintaining it. I don't think any fsspec maintainers have time to implement that on their own right now. From dvc perspective, if it gets enough demand on dvc side - we (dvc team) might consider working on it, but it is unlikely to happen any time soon. Let's continue discussion in https://github.com/iterative/dvc/issues/2432 , since your request is specifically dvc related.
