### ISSUE TITLE
samba backend

### ISSUE THREAD

**Issue by martindurant** [intake/filesystem_spec#306]
https://pysmb.readthedocs.io/en/latest/api/smb_SMBConnection.html appears to give a very thorough understandable interface to Samba for us to wrap, with random access. We can easily test these using one of the docker-based samba servers.

**Comment by telamonian** [comment]
I support this effort 100%. There's a dearth of vfs backends in general that support smb, and AFAIK there's only one [existing python smb vfs](https://github.com/althonos/fs.smbfs). A new solid python implementation would be very welcome.

WIth [jupyter-fs](https://github.com/jpmorganchase/jupyter-fs), I'm aiming to build a tool that sits at least one level above vfs backends in the stack (and so is backend agnostic). So far, all of the integrated backends are pyfilesystem-based, including https://github.com/althonos/fs.smbfs. I'll share what I've learned in the effort about smb + vfs.

The smb use case that people care about is the native Windows share client/server. Windows share is historically why the CIFS standard exists in the first place (and it seems like `MS-CIFS` is generally treated as the "real" standard). Windows is the source of all problems:

- In terms of getting started, it's very tricky to initialize a working client/server and test share on the Windows containers available on the public CI services. You

- `pysmb` doesn't cover all needed functionality. In turn, this is because the patchwork of standards on which `pysmb` is based don't cover eveything. The biggest pain point here that I've run into is that there is no specification/support for translating posix <=> windows file permissions.

- Focusing on the permissions issue, every vfs backend for smb has to roll their own "universal enough" posix/windows permissions handling. Instead, there's a [13 year old unaccepted draft spec](https://tools.ietf.org/id/draft-ietf-nfsv4-acl-mapping-05.txt) and (theoretically) a reference implementation somewhere in the code of the OSS samba server (see notes under "Interoperability Strategies" [here](https://wiki.linux-nfs.org/wiki/index.php/ACLs)).

**Comment by juarezr** [comment]
The package pysmb only handles SMB protocol v2.

The PR #340 has a implementation using the [smbprotocol](https://github.com/jborean93/smbprotocol) package.
