### ISSUE TITLE
Update HDFSFile to inherit from AbstractBufferedFileSystem

### ISSUE THREAD

**Issue by ayushdg** [intake/filesystem_spec#337]
Currently most Filesystem implementations in `fsspec` on opening a file (`fs.open(...).open()`) return an object that is an instance of `io.IOBase`. While [HDFSFile](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/hdfs.py#L177) is a wrapper around Arrow's HdfsFile (which is an instance of `io.IOBase`), and exposes all it's attributes via `__getattr___` the class itself is not an an instance of `IOBase`.

Note: I'm guessing this feature was intended for the future based on the comment [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/hdfs.py#L194).

**Comment by martindurant** [comment]
Why would you want a strict class hierarchy as you suggest? There are other file objects returned by the various backends that might not inherit from AbstractBufferedFile or IOBase. The *point* is, that they should duck-type to be able to be used in any file-like situation, which HDFSFile does. It would be tricky to implement otherwise, because getattr only gets called it the given attr isn't defined, but in the inherit case we would have the base class default implementations (giving NotImplementedError).

**Comment by ayushdg** [comment]
Thanks for the explanation.
For context: My use case was converting the buffer from the open file object object in python down to something that can be passed down the cpp. Currently I check for objects that inherit from `io.IOBase`, it's simple to define how to get the buffer/ other attributes for such objects. Perhaps it makes more sense to check if it has certain attributes that would determine if what was passed down was indeed `file-like` (rather than checking if it's an instance of `io.ioBase`), or possibly wrap the fsFileobject with an `ioBase` like object.

**Comment by martindurant** [comment]
The object guarantees that the fie-like methods (read, seek, tell, etc) work, but I wouldn't think you could rely on accessing the inner buffer stuff the same across different file classes anyway. You cold indeed wrap the object in an io.BufferedIOBase, or find out exactly which methods you need. Alternatively, you could get all the bytes (`cat`) and use with `io.BytesIO`, or use `fsspec.open_local("simplecache::hdfs://path/file")` to copy to local and pass a real local file path to your C++ code.

**Comment by ayushdg** [comment]
Thanks for those suggestions @martindurant!
