### ISSUE TITLE
use of 'az' as a shorter version of 'abfs`

### ISSUE THREAD

**Issue by raybellwaves** [intake/filesystem_spec#373]
This is more of a discussion than a features request.

Looking at `known_implementations` there are `gcs` and `gs` which both point to `gcsfs.GCSFileSystem`. Could `az` be created as a shorter version of `abfs`?

- `az` is common with Azure CLI syntax e.g. https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#run-azcopy.
- As someone who is very lazy I prefer two key strokes instead of four.

**Caveats**

Unlike `gs` and `s3`, Azure has two classes (`adlfs.AzureDatalakeFileSystem` and `adlfs.AzureBlobFileSystem`). I imagine you can't use `az` for both classes.

**Proposed solution**

Use `az` as a shortcut for `'abfs': {'class': 'adlfs.AzureBlobFileSystem'}`. Given this is for the latest version of storage (Azure Datalake Gen2 and Azure Blob Storage). In addition my 50 % reduction in key strokes motivation doesn't apply to `adl` (Azure Datalake Gen1).

If you prefer me to open at https://github.com/dask/adlfs I will do so.

**Comment by martindurant** [comment]
> az is common with Azure CLI syntax

This is a good enough reason for me; but yes, please ask on the adlfs repo, to poll for preferences.

Note that at some point I really want to implement an entrypoints method for packages to declare the fsspec drivers they contain, so that the protocol string is listed in one place only. However that wouldn't solve the case where a protocol driver is *not* installed and the user could do with a nice message telling them whet to do about it.
