### ISSUE TITLE
md5 incompatible with FIPS enabled OS

### ISSUE THREAD

**Issue by klucar** [intake/filesystem_spec#380]
For [FIPS ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sect-security_guide-federal_standards_and_regulations-federal_information_processing_standard) enabled operating systems (think AWS GovCloud), md5 isn't allowed because FIPS deems it insecure. (even though it's just being used as a local cache lookup key) 

The below line of code fails on fips enabled systems because Python's md5 uses the system openSSL library, and FIPS blocks md5.

https://github.com/intake/filesystem_spec/blob/f29c59c2c9a8b37cf8a9ed5e3956e4a7708e235c/fsspec/utils.py#L278

FIPS will allow sha256, so that is a potential solution, or some other cache index mechanism can be developed.

**Comment by cpbrophy** [comment]
63a668fb4a60d41efc66c5f6445b6a500d5e4396 appears to undo this fix.

**Comment by martindurant** [comment]
Is there a middle ground, something that is fast for hashing but not falling foul of security?

**Comment by cpbrophy** [comment]
Something like [this approach](https://code.djangoproject.com/ticket/28401) that django came up with might be a middle ground?

**Comment by martindurant** [comment]
A little local testing actually suggests blake2b with digest_size=8 is faster than both sha and hd5, and is considered secure. Will that do?

**Comment by martindurant** [comment]
I assume the `zlib` (numerical) hashes are also forbidden?

**Comment by cpbrophy** [comment]
Well annoyingly it turns out that even though blake2 is considered to have a ["large security margin"](https://nvlpubs.nist.gov/nistpubs/ir/2012/NIST.IR.7896.pdf) it [still isn't FIPS approved](https://research.kudelskisecurity.com/2017/03/06/why-replace-sha-1-with-blake2/), so trying that out didn't work. For whatever reason though, there's no error using `zlib.crc32` so go figure.

**Comment by cpbrophy** [comment]
Just my opinion, but this seems like a less silly workaround than going the zlib route:

```python
def tokenize(*args, **kwargs):
    """Deterministic token

    (modified from dask.base)

    >>> tokenize([1, 2, '3'])
    '9d71491b50023b06fc76928e6eddb952'

    >>> tokenize('Hello') == tokenize('Hello')
    True
    """
    if kwargs:
        args += (kwargs,)
    try:
        return blake2b(str(args).encode()).hexdigest()
    except ValueError:
        return md5(str(args).encode(), usedforsecurity=False).hexdigest()

**Comment by martindurant** [comment]
Can it be guaranteed that FIPS is the only thing that can cause an exception during blake hashing, and that in those systems `usedforsecurity=False` will be available?

**Comment by efiop** [comment]
How much performance are we gaining from using md5 instead of sha*? Depending on this, maybe we could just switch to sha* and forget about it. Having a conditional hash algorithm for tokenize will mean that we need an additional "persistent" tokenizer for stuff that can be shared between machines (e.g. for fsid feature or for persistent dircache).

We have a very similar problem in dvc, where we've been historically using md5, but people have been requesting other hashes. With FIPS in mind, we are pretty sure we will be switching to sha.

**Comment by martindurant** [comment]
You may add of order 20% to the hash time, which is the dominant factor in the token function, and can add up when performed many many times (i.e., there was a reason it got noticed!).

**Comment by cpbrophy** [comment]
> Can it be guaranteed that FIPS is the only thing that can cause an exception during blake hashing, and that in those systems `usedforsecurity=False` will be available?

Based on what I see in the source for [hashlib](https://github.com/python/cpython/blob/3.6/Lib/hashlib.py), I believe that will be the case from python3.6 and later, where blake2 is added to the "always supported" list. When a ValueError is encountered by the call to openssl it falls back to the builtin, unless operating in FIPS mode in which case the error bubbles up.

**Comment by martindurant** [comment]
We seem to have not come to a consensus here. What do people think we should do?

**Comment by martindurant** [comment]
https://github.com/fsspec/filesystem_spec/pull/872

**Comment by cpbrophy** [comment]
Much appreciated, thanks!
