### ISSUE TITLE
MemoryFileSystem duplicates directories

### ISSUE THREAD

**Issue by FHTMitchell** [intake/filesystem_spec#422]
By creating a directory and then creating a file within that directory, `fsspec.implementations.memory.MemoryFileSytem` will register that directory as appearing twice in the original root directory.

## Example

```python
import fsspec
fsspec.__version__
Out[3]: '0.8.2'

from fsspec.implementations.memory import MemoryFileSystem
fs = MemoryFileSystem()
fs.touch('a/b/c.d')
fs.ls('a')
Out[4]: ['a/b/']   # correct

fs = MemoryFileSystem()
fs.mkdir('a/b')
fs.touch('a/b/c.d')
fs.ls('a')
Out[5]: ['a/b/', 'a/b/']   # incorrect
```

**Comment by martindurant** [comment]
Thanks for the report. It would be good to check the values of the interior store and pseudodirs to see why this is happening. It should be an easy fix, and your code will make a good test.

**Comment by FHTMitchell** [comment]
Sure, the problem is we are setting the mutable `store` and `psuedo_dirs` as global class variables, rather than instance variables. This means every class created keeps the values of previous ones.

```python
class MemoryFileSystem(AbstractFileSystem):
    """A filesystem based on a dict of BytesIO objects"""

    store = {}  # global
    pseudo_dirs = []
    protocol = "memory"
    root_marker = ""
```

I have a PR ready to go if you're happy with that?

**Comment by martindurant** [comment]
Actually, I don't think that's a problem as such - this implementation is for a single global memory store. It could have been instance-wise.

I think the trouble actually is in the `ls` implementation, where we both record "implicit" directories due to deeper-nested file entries *and* the contents of pseudo_dirs. We could change
```
if ppath not in paths
```
to
```
if ppath not in paths and ppath not in self.pseudo_dirs
```
(two locations)

**Comment by FHTMitchell** [comment]
Ah yes, that is the reason for the duplicates in `ls`. What I said is why they don't disappear between instances.

On another note, I I think that's a curious (undocumented) implementation decision considering this is (I expect) primarily going to be used for testing where you want tests to be independent of each other.

**Comment by martindurant** [comment]
I can't remember now why, but there *was* a reason, I promise. It would be reasonable to provide an arg on the constructor which gives instance-wise stores (perhaps by default) or global. Note that, because of instance caching, `MemoryFileSystem() is MemoryFileSystem()` but `MemoryFileSystem() is not MemoryFileSystem(skip_instance_cache=True)`.

**Comment by FHTMitchell** [comment]
Fair enough, I've linked a PR to solve the immediate problem. I'd be happy to work on a feature to give instance wise stores in another issue.
