### ISSUE TITLE
Libarchive extension

### ISSUE THREAD

**Issue by juliospain** [intake/filesystem_spec#445]
Hi, based on the zip filesystem, I have done an extension for the libarchive (which can be used to read/write several compressed files formats):

[gist](https://gist.github.com/juliospain/e272e50c54f001a9c9f1844ebe0fb5ff)

For now it has some limitations:
1. Only read is allowed (anyway, the write is a little bit awkward with this library)
2. All files are extracted in memory. The library has some limitations, and it is not re-entrant (file descriptor position needs to be kept from one block read to the next). To have several "open files" at the same time would mean having the archive file open several times as well, which for my particular application seemed undesirable.

My next idea is that it could be extended to register some extensions and allow paths like:
c:/somezip.7z/file_inside.txt
be converted to:
libarchive:/file_inside.txt::c:/somezip.7z
and also integrate it into the pathlib discussions.

Probably very focused in my current use case, but still, maybe is of interest of someone.

**Comment by martindurant** [comment]
> My next idea is that it could be extended to register some extensions and allow paths like:
c:/somezip.7z/file_inside.txt
be converted to:
libarchive:/file_inside.txt::c:/somezip.7z

You imagine automatically recognising specific file extensions? This might provide some problems, because it's perfectly possible that someone want to open the binary compressed file. I'm not sure, in practice, how you would do this within fsspec now.

Note that `fsspec.open` support compression for whole files (gzip, snappy, xz, ...). 7z and rar files are always used to store multiple files? Do any of them offer internal blocking, so that you have something like random access? Sorry for my ignorance here.

Ref: https://github.com/intake/filesystem_spec/pull/305 (tar is certainly **bad** for this kind of thing, but maybe of interest here. In that case, we can do OK for uncompressed, if we first scan the file for all the offsets of the contained files)

**Comment by juliospain** [comment]
Yes, could be problematic, it is a rough idea, but for example archive.7z would allow reading the file, while archive.7z/ reading the contents.

This libarchive extension is more oriented in multi-file archives. Specially 7z has a very nice compression ratio compared to zip for example. In particular 7z does not allow any kind of random access, and neither the library (libarchive), to seek a particular file (it is understood the overhead of going through the file descriptors is not that big), and then the reading of a particular file is also done sequentially.
It can look very limiting but for a lot of use cases, one would read the file only once in a sequential order.

I will work more on this to polish it...
