### ISSUE TITLE
fsspec 0.9.0 breaks quetz

### ISSUE THREAD

**Issue by beenje** [intake/filesystem_spec#607]
Hello,
I found an issue in [quetz](https://github.com/mamba-org/quetz) that I tracked down to fsspec 0.9.0. It works fine with version 0.8.7. Maybe the issue is in how quetz uses fsspec, but I thought it was better to report it here as I saw other issues linked to 0.9.0 mentioned here.

When trying to read a file, the following exception is raised:
```python
  File "/Users/benjaminbertrand/Dev/conda/quetz/quetz/main.py", line 1600, in iter_chunks
    data = fid.read(chunk_size)
ValueError: read of closed file
```

Relevant function is [here](https://github.com/mamba-org/quetz/blob/9b344228458db6add87bc13c3ac368f874aa97fe/quetz/main.py#L1598):

```python
    def iter_chunks(fid):
        while True:
            data = fid.read(chunk_size)
            if not data:
                break
            yield data

    package_content_iter = iter_chunks(
                pkgstore.serve_path(channel.name, path + '.gz')
            )
```

The [serve_path](https://github.com/mamba-org/quetz/blob/9b344228458db6add87bc13c3ac368f874aa97fe/quetz/pkgstores.py#L138) function just does:

```python
    def serve_path(self, channel, src):
        return self.fs.open(path.join(self.channels_dir, channel, src)).f
```

where `self.fs: fsspec.AbstractFileSystem = fsspec.filesystem("file")`.

Is there some API change that could explain this?

**Comment by martindurant** [comment]
This is not exactly an API change, but a subtle thing.

When you execute 
```
fs.open(path.join(self.channels_dir, channel, src)).f
```
the `open` creates a `LocalFileOpener` (if this is not local files, please correct me). This object was changed to be a subclass of `IOBase` recently, so that packages that wanted to check if the resulting object was file-like would be satisfied. It can be used directly in place of a file, you do not need `.f` (which maybe should be a private `._f`.

However, when you select the `f` attribute and forget the original `LocalFileOpener`, the latter gets garbage-collected. This didn't used to matter, but now the superclass `IOBase` calls `close` - which closes the underlying file too.

```
fs = fsspec.filesystem('file')
fs.open('localfile').f # LocalFileOpener immediately collected
assert f.closed
```

```
fs = fsspec.filesystem('file')
lfo = fs.open('localfile')
assert not lfo.f.closed  # was not collected if we keep the reference
```

The short answer is:
Do `return self.fs.open(path.join(self.channels_dir, channel, src))` without the `.f`.

**Comment by beenje** [comment]
Thanks a lot for the quick feedback and the explanation!
I guess this issue can be closed.
