### ISSUE TITLE
How to use fsspec with persistent local cache in a predefined directory

### ISSUE THREAD

**Issue by ophiry** [intake/filesystem_spec#88]
I'm looking for more details about using local cache with fsspec
specifically:
1. how to specify if using cache
2. how to specify if the cache should be cleaned on process exit
3. how to control the location of the cache
4. if a file is in the cache, I assume the version of the file is checked to verify the cache is up to date - is it possible o disable this? (for cases I trust the remote files don't change)

**Comment by martindurant** [comment]
You should know that the cache implementation is very experimental, so use at your own risk.

1) you can either invoke `fsspec.implementations.cached.CachingFileSystem` directly, or use the top level `fsspec.filesystem('cached')`, and pass as arguments the protocol and further arguments needed by the target FS
2) the cache is *not* cleaned. Unless otherwise specified, it is put in a temporary directory, so the OS may clean it depending on its settings
3) The `cache_storage` kwargs
4) There is no version checking at all. It is possible to have horrible inconsistency if the target file changes. In general, only some FS implementations will be able to offer reliable version information.
